### ISSUE TITLE
Configure logging to go through spring-jcl

### ISSUE THREAD

**Issue by snicoll** [neo4j/neo4j-java-driver-spring-boot-starter#1]
Currently there is a `logging-class` property that allows the user to specify how logging should work. The auto-configuration has [some logic to detect the right implementation](https://github.com/neo4j/neo4j-java-driver-spring-boot-starter/blob/4f85158747efda60905823302b9083d99a3d50ed/neo4j-java-driver-spring-boot-autoconfigure/src/main/java/org/neo4j/driver/springframework/boot/autoconfigure/Neo4jDriverProperties.java#L471-L485).

An alternative would be to register a simple logging implementation that uses `spring-jcl`. Regular spring apps that don't customize the logging system will work out-of-the-box. I'd also remove the property: FQN are usually configured via a customizer rather than via a property.

**Comment by michael-simons** [comment]
Thanks for the input. 

We'll use Spring JCL in the new Spring Data Neo4j as well (instead of SF4J directly, which is the case in current SDN and AFAIK in some other Spring Data projects, too).
