### ISSUE TITLE
Neo4jHealthIndicator: Use read transaction instead of the session to execute the cypher query 

### ISSUE THREAD

**Issue by microvish** [neo4j/neo4j-java-driver-spring-boot-starter#31]
Transactions can automatically handle transient errors using an automatic retry mechanism. This eliminates false positives health indicators especially where bolt routing is involved.

Reference: https://neo4j.com/docs/driver-manual/1.7/sessions-transactions/#driver-transactions-transaction-functions

Example: -

```
try (Session session = this.driver.session(DEFAULT_SESSION_CONFIG)) {
  session.readTransaction(transaction -> {
    final Result result = transaction.run(CYPHER);
    ...
  }
}
```

**Comment by michael-simons** [comment]
Good point.
