### ISSUE TITLE
Neo4jDriverProperties class is missing

### ISSUE THREAD

**Issue by dayelostraco** [neo4j/neo4j-java-driver-spring-boot-starter#35]
We are attempting to implement the Spring Data Dedicated Routing Driver documented in section 3.7 of the Neo4j Spring Boot Starter documentation (https://neo4j.github.io/neo4j-java-driver-spring-boot-starter/current/). However, the import statement for Neo4jDriverProperties (import org.neo4j.driver.springframework.boot.autoconfigure.Neo4jDriverProperties;) is not located in the classpath.

Is there a new manner in which Spring Boot Neo4j Starter applications are to connect to a Neo4j cluster with Bolt+Routing?

We are using Spring Boot Starter Parent 2.3.2.RELEASE.

Thanks!

Dayel Blake

**Comment by michael-simons** [comment]
Hi @dayelostraco Sorry I must have missed the notification… 

You need to add this starter to the project manually. It doesn't come with Spring Boot prior to 2.4. automatically.
